version: '2'
services:
    workout-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/workout/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=workout
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
